DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY,
    username varchar(64) unique not null,
    password varchar(255) not null,
    fname varchar(64) not null,
    lname varchar(64),
    dateOfBirth DATE not null,
    bio TEXT,
    avatar TEXT not null,
    isAdmin BOOLEAN default FALSE
);

CREATE TABLE articles (
    article_id INTEGER NOT NULL PRIMARY KEY,
    title TEXT not null,
    content TEXT not null,
    summary TEXT not null,
    date timestamp not null,
    image TEXT,
    author_id INTEGER not null,

    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    comment_id INTEGER NOT NULL PRIMARY KEY,
    content TEXT not null,
    date timestamp not null DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER not null,
    article_id INTEGER not null,
    parent_comment_id INTEGER,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (article_id) REFERENCES articles(article_id) ON DELETE CASCADE,
    FOREIGN KEY (parent_comment_id) REFERENCES comments(comment_id) ON DELETE CASCADE
);

CREATE TABLE likes (
    like_id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER not null,
    article_id INTEGER not null,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (article_id) REFERENCES articles(article_id) ON DELETE CASCADE,
    UNIQUE (user_id, article_id)
);

insert into users(id, username, password, fname, lname, dateOfBirth, bio, avatar, isAdmin) values
    (1, 'rizkiputra660', '$2b$10$a7jJkhwT6IHt/qNcMO9bE.o58f5vTRpTiESK/qHoLYTaWqL5HmuWe', 'Rizki', 'Putra', '2000-06-10', 'I love Demon Slayer', '/images/avatars/inosuke.png', true), 
    (2, 'tanjirokamado', '$2b$10$cdlXBCRdqC5zewVUicTuNu2wmeBr1eRfq6UTtWjtFlYg.kDmbCrFW', 'Tanjiro', 'Kamado', '2000-07-14', 'I am the main character of Demon Slayer. I mastered Sun and Water Breathing Techniques.', '/images/avatars/tanjiro.png', false);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(1, 'Tanjiro Kamado', "<p>Tanjiro is a young boy of average height with fairly tanned skin and an athletic, muscular physique. He has ruffled black hair with red tips (and being entirely only burgundy in the anime), combed back to expose his forehead, and wide, dark red eyes with white pupils that appear lighter around the lower section of his irises. He also has a scar on the top left of his forehead, first seen when his mother brought him to watch his father perform the Hinokami Kagura dance. The scar originally looked somewhat like a graze until his fight with the Hand Demon during Final Selection, after which it developed into a flame-like pattern as his Demon Slayer Mark. It is noted that his hands are visibly rougher for someone his age, as a result of his rigorous training under Sakonji Urokodaki. Tanjiro looks remarkably similar in appearance to his ancestor Sumiyoshi Kamado, possessing the same facial structure, eyes, and hairstyle as him, although Sumiyoshi's hair was longer, about shoulder-length, and would be tied in a ponytail behind his head.</p>

<p>Tanjiro is very kind by nature and has been described by others as having very gentle eyes and a compassionate persona. He exhibits a great deal of determination and will not give up once he has a goal to achieve; the best example of this is his relentless quest to find a cure for Nezuko. Even though he is relatively strong on his own, Tanjiro isn't opposed to asking others for help when he needs it. He is very protective of his friends, and even more so of his younger sister. However, despite his kind and understanding nature, Tanjiro does have a limit to his tolerance and has a distaste for rudeness and cowardice, as he easily becomes annoyed by Zenitsu Agatsuma's constant whining and angered by Inosuke Hashibira's barbaric actions.</p>

<p>From the beginning, Tanjiro was shown to be a prodigious fighter, having a strong natural aptitude for combat, especially swordsmanship. Tanjiro was already introduced to have above-average human abilities, like honed senses, a sharp sense of smell, immense willpower, and great intellect. His naturally obtained abilities go so far as to allow him to outsmart and catch Giyu Tomioka, one of the most powerful Demon Slayers, off guard and nearly land a fatal blow on him despite being clouded with intense emotions. Moreover, in his first encounter with a demon, Tanjiro managed to slash the neck of the Temple Demon and impress him, later being able to fend the demon off with a regular hatchet and come up with unique solutions such as using his durable head to headbutt the Temple Demon and also using his hatchet to pin him down and prevent him from moving.</p>", "Tanjiro Kamado is the main protagonist of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer in the Demon Slayer Corps who joined to find a remedy to turn his sister, Nezuko Kamado, back into a human and to hunt down and kill demons, and later swore to defeat Muzan Kibutsuji, the King of Demons, in order to prevent others from suffering the same fate as him.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/tanjiro.jpeg', 1);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(2, 'Nezuko Kamado', "<p>Nezuko is a young girl with fair skin, visibly large, prominent fangs, a slender build, and sharp, stiletto nails with a base color of light pink and ombre fading to a red-pinkish color at the end where they point. Her hair is long, black, and wavy. It reaches just below her waist, turning a flame-orange color as it passes her elbows, and appears to be crimped into large, straight ridges, worn side-swept drastically to her left. She has soft-looking, pale pink eyes that appear a lighter color around the rims of their irises and on the center a persian pink below the pupils; they slanted downwards toward the sides of her face and framed by notably long eyelashes. Her pupils appear as black slits as she transforms. In the manga, Nezuko can sometimes be shown with more than one bow. According to Tanjiro, Nezuko was known as a great beauty in their home town.</p>

<p>Nezuko's original personality as a human was that of a kind and caring girl who thought of others before herself, much like her older brother, Tanjiro. Additionally, she was a responsible elder sister to her younger siblings and often put their needs before her own.Nezuko is, however, not afraid to get in harm's way, protecting her friends from demons even after being returned to a human state. It is also shown that Nezuko's humane, laid-back demeanor supports this fact after Tanjiro apologizes to her.</p>

<p>Despite not being a member of the Twelve Kizuki, Nezuko is a very powerful demon. Her most prominent trait is her extraordinary growth rate, due to the high amount of blood she received from Muzan Kibutsuji when he turned Nezuko into a demon. This was shown in many battles where she could defeat her enemies despite being overwhelmed by them in the beginning. She has been shown to defeat her enemies by increasing her own physical capabilities, enhancing her regeneration, or developing her own Blood Demon Art in dire situations.</p>", "Nezuko Kamado is the deuteragonist of Demon Slayer: Kimetsu no Yaiba. She is a demon and the younger sister of Tanjiro Kamado and one of the two remaining members of the Kamado family. Formerly a human, she was attacked and transformed into a demon by Muzan Kibutsuji.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/nezuko.jpeg', 1);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(3, 'Zenitsu Agatsuma', "<p>Zenitsu is a young man of average height with fair skin and downward-sloped, worried-looking eyes that fade from soft brown to gold and golden, forked eyebrows that sharply fade into a warm orange color. He has short, yellow hair of varying lengths, cutting off squarely at the ends where it fades to a darker orange color, that falls in front of his face in uneven bangs, loosely resembling a bowl cut. Before he became a Demon Slayer, Zenitsu's hair was originally black, but it turned the color it is currently when he was struck by lightning during his training.</p>

<p>Zenitsu is cowardly, nihilistic, weak-willed, and anxious, often claiming that he doesn't have long to live due to the dangerous job of being a Demon Slayer. He has rather low self-esteem despite his talent and strength, even considering himself useless. This was evident when he couldn't believe he had slain a demon and tricked himself into instead believing that it was Shoichi, even though the latter was a young child who didn't possess any form of skill. Zenitsu is in a constant state of fear, and he frequently tries to run away at the sight of danger, claiming he wants to live a modest, normal life instead of that of a Demon Slayer. Due to this, Zenitsu screams and shouts a lot, much to the annoyance of the people around him. He is also shown to be pessimistic at times, especially during Hashira Training, where he lashed out at Tanjiro and Inosuke for viewing the training positively.</p>

<p>From the beginning, Zenitsu comes off as a talented and skilled Demon Slayer, though he denies this. His strength awakens when he is asleep, as his nervous demeanour is what normally keeps him from accessing his abilities, making him more sagacious, calm, and precise in combat. This allowed him to instantly decapitate the Tongue Demon and defeat the Son of the Spider Family by himself. He was later able to defend three entire train carts being attacked by Enmu, Lower Rank One, along with Nezuko. A few months after that, he was able to go toe-to-toe with an awakened Daki with the assistance of Inosuke, and later managed to blitz her with Thunderclap and Flash: Godspeed. As further credence to his strength, Zenitsu was able to advance to the highest point of the Hashira Training.</p>", "Zenitsu Agatsuma is one of the main characters of Demon Slayer: Kimetsu no Yaiba and along with Inosuke Hashibira, a travelling companion of Tanjiro Kamado and Nezuko Kamado. He is also a Demon Slayer in the Demon Slayer Corps.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/zenitsu.jpeg', 1);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(4, 'Inosuke Hashibira', "<p>Inosuke is a young man of average height and pale complexion with an extremely toned and muscular build for his age. In sharp contrast to this, he has an incredibly pretty and feminine face, with large, wide eyes that are framed by an array of long eyelashes, their iris a dark to soft pale green, thin eyebrows, and what could be a small, well-mannered mouth. His thick, raven-black hair reaches just past his shoulders, fading into blue at the tips and forming an unruly and uneven fringe that falls just above his eyes, puffing out before curving and thinning towards his forehead.</p>

<p>Inosuke is short-tempered, confrontational, abrasive, and proud. He always likes to think he is the strongest fighter in a situation, constantly challenging most people he comes across and wanting others to respect and praise him for his skill. This often leads him into unnecessary danger since he tends to overestimate his abilities in comparison to who he's fighting and refuses to accept when he's been defeated, which can be seen when Giyu Tomioka has to tie him up after his fight with the Father to prevent him challenging the Hashira to a fight while still severely injured from his previous battle. This constant wanting to be the best can also cause Inosuke to be very provocative, as he often tries to goad others, most prominently Tanjiro Kamado, into fighting him, although in the case of the latter he usually fails due to Tanjiro's obliviously kind nature.</p>

<p>Inosuke is a very skilled and talented swordsman, as he was able to learn Total Concentration Breathing on his own, develop his very own Breathing Style known as Beast Breathing based on his own instincts and upbringing in the mountains by wild boars, and pass Final Selection to become a Demon Slayer all without formal training. Inosuke is more than capable of hunting and slaying demons on his own, as he easily killed the Horned Demon without any trouble. He has shown on multiple occasions to be able to hold his own and contribute in fights against Upper Rank demons of the Twelve Kizuki, including Upper Rank Six, Gyutaro and Daki, as well as the much stronger Upper Rank Two, Doma. He is also incredibly gifted, possessing inhuman senses and superhuman flexibility, as well as a natural aptitude for combat. Most impressively, Inosuke was able to fend off the Demon King, Muzan, along with his fellow comrades, boasting the same combat proficiency as even the Hashira, the strongest swordsman among all the Demon Slayers.</p>", "Inosuke Hashibira is one of the main characters of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer in the Demon Slayer Corps and a travel companion of Tanjiro Kamado and Nezuko Kamado along with Zenitsu Agatsuma.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/inosuke.jpeg', 1);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(5, 'Kanao Tsuyuri', "<p>Kanao is a girl of short stature, with large and gentle eyes of a dark lilac color that are framed by thick eyelashes. She has short, thin raven-black hair, tied into a ponytail on the right side of her head and fastened by a pink and green butterfly ornament that once belonged to her adoptive sister, Kanae Kocho. She has a straight fringe and two loose, chin-length strands that curve downwards from above each of her ears.</p>

<p>At first, Kanao was an indecisive and quiet girl due to the abuse she endured in her past before meeting the Kocho sisters. She became unable to make decisions by herself and repressed her emotions as a defense mechanism. In order to help rectify this, Kanae Kocho gave her a coin to flip to decide which path to follow when she didn't know what to do. For many years, Kanao continued to show little emotion or desire. Despite this, after seeing what demons did to Aoi Kanzaki, Kiyo Terauchi and Shinobu Kocho's loved ones, Kanao developed a strong hatred against demons directly from her own will. Shinobu, oblivious to this fact, was afraid that she wasn't acting on her own volition.</p>

<p>Kanao is the Tsuguko of Kanae Kocho and Shinobu Kocho who has been personally trained by the both of them in the art of combat. As such, Kanao possesses extremely refined physical abilities, sharpened skills and prowess that potentially marks her as a future member of the Demon Slayer Corps' Hashira. Tanjiro Kamado, another promising candidate, even states that, during their first meeting together, he could already sense that Kanao was the closest to the Hashira out of the existing Demon Slayers, just by smelling her scent and feeling her aura, which further confirms her skills. Later during her battle against Doma, the second most powerful of the Upper Ranks, he acknowledged her abilities to have surpassed that off Shinobu's.</p>", "Kanao Tsuyuri is a major supporting character of Demon Slayer: Kimetsu no Yaiba. She is a Demon Slayer of the Demon Slayer Corps, Shinobu Kocho's Tsuguko and the adopted sister of Shinobu and Kanae Kocho.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/kanao.jpg', 1);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(6, 'Giyu Tomioka', "<p>Giyu is a fairly tall young man of a lean muscular stature and pale complexion, who is almost always seen wearing a stoic expression. He has choppy raven-black hair of uneven lengths, with jaw length side-bangs, a low messy ponytail at the base of his neck, and bangs falling over his eyes in an choppy fringe. His eyes are sharp and moderately large, having irises a lapis blue color, and their pupils a navy blue, sometimes having his irises completely opaque and empty, just in lapis blue color, and are framed by thin eyebrows.</p>

<p>Giyu is a man of strong equanimity, always wearing a calm and stern expression on his face. Having a stoic personality, and possessing a very strong sense of justice and responsability, he had no tolerance towards those who don't know their own limitations and throw away their lives. Despite letting Nezuko Kamado live due to Tanjiro Kamado's determination, he shows zero hesitation when killing other demons and has no respect or mercy towards them like most Demon Slayers. Even so, Giyu violated the Demon Slayer Corps' code of conduct without hesitation to protect Nezuko during Shinobu's attempt to kill her. This implies that he doesn't completely despise demons as some other Hashira do, and is willing to make an exception for a demon by letting them live if they don't kill and eat humans. This shows that he is more pragmatic and impartial in dealing with demons rather letting his hatred cloud his judgement.</p>

<p>As a Hashira of the Demon Slayer Corps, Giyu is a very powerful and skilled combatant. From the beginning, Giyu showed how much he outclassed Tanjiro and his friends, being able to effortlessly capture Nezuko from him and later knocked both of them unconscious in a single blow. Later, he was able to easily defeat Father in his transformed state and Rui, Lower Rank Five, something Tanjiro and Inosuke respectively failed to accomplish. He also fought equally against fellow Hashira Sanemi Shinazugawa in a sparring match. Giyu was also shown easily beating dozens of demons equal to that of the Lower Ranks of the Twelve Kizuki. On top of his incredible skills as a Demon Slayer, Giyu is also a very capable teammate, able to grasp their intentions and work in tandem with it.</p>", "Giyu Tomioka is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the Water Hashira of the Taisho era.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/giyu.jpeg', 2);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(7, 'Sanemi Shinazugawa', "<p>Sanemi is a tall man of very muscular build, with spiky long white hair and large almond-shaped eyes framed with long eyelashes; his purple irises also appear to have dark swirls within them. When angered, they appear notably bloodshot. He also has dark patches beneath his eyes, making him appear perpetually tired or restless. His face and body are covered with scars, accrued over his many years of fighting demons. He cuts his hair short somewhere in between the events of the Hashira meeting and the Mugen Train incident. He is usually seen wearing a crazed expression on his face.</p>

<p>Sanemi is abrasive, hot-blooded, rash, and stubborn, often times impulsive and quick to lash out. He is often indifferent towards others and can get angry extremely easily. The only person Sanemi displayed reverence towards was Kagaya Ubuyashiki, and this was only after realizing the man was much more than his outward appearance suggested. Sanemi has also displayed a hunger for battle, wishing that he could encounter Upper Rank demons and proclaiming his excitement in fighting Upper Rank One, Kokushibo.</p>

<p>As a Hashira of the Demon Slayer Corps, Sanemi is a very powerful and skilled combatant. He has displayed his extraordinary abilities and proficiency in combat on multiple occasions. When sparring with Giyu Tomioka, Sanemi was able to fight on equal grounds with the Water Hashira. In the battle within the Infinity Castle, Sanemi was shown to be capable of instantly annihilating hordes of demons that were comparable to the Lower Ranks in strength. Most notably, he could hold his own against Upper Rank One, Kokushibo. According to the demon, Sanemi's physical abilities and techniques have reached their peak. Kokushibo also commented that Sanemi and the accompanying Gyomei Himejima stood out as highly skilled even among the ranks of the already powerful Hashira. After the Upper Rank was defeated, Sanemi was quick to recover from the death of his brother and proceeded to assist the Demon Slayers against the Demon King, Muzan Kibutsuji. He played pivotal roles in damaging the demon in conjunction with the attacks of the other combatants and was one of the two Hashira to survive to see the end of the monumental battle.</p>", "Sanemi Shinazugawa is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the Wind Hashira of the Taisho era.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/sanemi.jpeg', 2);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(8, 'Muzan Kibutsuji', "<p>Muzan is a tall man with a lean muscular build along with an unnaturally pale skin complexion that can be easily confused as being unhealthy and sickly. He has curly black hair and sharp, almond-shaped eyes. His irises are cat-like in appearance and are of a plum red color. He also possesses sharp, blue nails on his hands. Physically, he appears to be in his twenties.</p>

<p>Muzan is cold-hearted, ruthless, intimidating, and exceptionally intelligent. He sees no value in any humans he has encountered and shows little value in his own subordinates. Rarely ever visibly upset or happy, he appears completely monotone and detached on most occasions, even when he callously murders his own subordinates. The only times he ever shows emotion are when his vision of perfection is moving forward or when he has subordinates completely submit to his will. Initially, his expressions would only change slightly and only bear a slight shift from his usual calm attitude and his tone of voice tends to be consistent at nearly all times, accentuating his monotonous demeanor. His cruel and imposing nature has gained him the great admiration and fear of many demons.</p>

<p>As the Demon King, the first and the progenitor of his kind, Muzan is the strongest demon in existence. Even after dissolving a drug that was supposed to weaken his powers and turn him back into a human, Muzan easily annihilated close to a hundred Demon Slayers in a short period of time effortlessly. In his bout with a marked Giyu Tomioka and Tanjiro Kamado, the former stated that an Upper Rank's strength is incomparable to Muzan's, while the latter was unable to even follow his attacks and could only dodge by pure instinct. After Tanjiro got close to the Demon King, Muzan nonchalantly slashed out Tanjiro's eye, and he later stated that his attacks were too fast for him to detect through smell.</p>", "Muzan Kibutsuji is the main antagonist of Demon Slayer: Kimetsu no Yaiba. He is the Demon King, the progenitor of all other demons in existence, and the leader of the Twelve Kizuki, an organization made up of the twelve strongest demons under his direct command.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/muzan.jpeg', 2);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(9, 'Kokushibo', "<p>Kokushibo is a tall man of muscular build with a pale complexion. He possesses long, spiky black hair with red tips that he keeps in a ponytail. His most notable feature is the three sets of eyes on his face with yellow irises and red flesh sclera that have black straight lines diverging from each iris. His middle set of eyes has the kanji of 'Upper Rank (上じょう弦げん Jōgen?)' on engraved on his left eye, and daiji for 'One (壱いち Ichi?)' on his right, while his other sets of eyes feature black pupils and a cracked pattern in the irises. His top set of eyes replaced his eyebrows. Kokushibo also has red markings resembling flames on the top left side of his forehead and the bottom right of his chin. His appearance is described as profoundly majestic and dignified by Muichiro Tokito.</p>

<p>Kokushibo is reserved, silent, and aloof, maintaining an aura of unnerving tranquility and mystery that complements his position as Upper Rank One. He rarely speaks; when he does, he talks in a slow and emphatic manner that gives more gravitas and authority to his words. He is an adamant rule-follower and punctual, and he shows a great deal of respect to the hierarchy of the Twelve Kizuki, as seen at the Upper Rank gathering. Kokushibo is shown to be humble as well, and he did not hesitate to admit his failure or complain of any difficulty.</p>

<p>As the highest-ranking member of the Twelve Kizuki, Kokushibo is an extraordinarily powerful demon, second only to the Demon King Muzan Kibutsuji himself. He has battled countless Demon Slayers and has amassed vast experience and knowledge over his nearly 500-year-long life. His abilities have been refined to the highest level, as he is not only a master of Total Concentration Breathing, but also a Marked individual who has gained access to the Transparent World, as well as the demon that possesses the highest concentration of Muzan's blood amongst the Upper Ranks.</p>", "Kokushibo is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the highest position, Upper Rank One.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/kokushibo.jpg', 2);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(10, 'Doma', "<p>Doma is a tall young man with a lean and muscular build. He is of extremely pale complexion and possesses unusually long, pointed nails that appeared to be stained with a pale blue color. He possesses long platinum blond hair that he wore parted to his right, the shorter parts around his face seeming to flare out to either side around his head, curving backwards with one lock slanting down to the right of his face to fall between his eyes, while the longer parts were left to drape centrally down his back in a thinning spiral. Due to his beauty, he was made a cult leader and seen as a divine being due to such.</p>

<p>Doma is outwardly friendly and cheery, possessing an approachable and charismatic air. Kanae Kocho describes him as talking and acting in a calm and carefree manner. However, it is soon revealed that Doma has psychopathic tendencies. He adopts sick beliefs and habits, such as devouring his cult's followers with the belief he is saving them from their suffering and pain. He believes he is saving them from their suffering by letting them live inside his body.</p>

<p>As the holder of the second highest ranking position of the Twelve Kizuki, and the third most powerful of his kind to have ever existed, Doma is an exceptionally powerful demon. His combination of combative prowess and his potent cryokinetic Blood Demon Art in battle is powerful enough to overwhelm and defeat the Insect Hashira, Shinobu Kocho, without any difficulty, and he is also noted to have defeated Kanae Kocho, the late Flower Hashira, in the past. Afterwards, Doma could take on both Inosuke and Kanao, whose strength and abilities were on par with the Hashira, simultaneously without much effort either.</p>", "Doma is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the second highest position, Upper Rank Two.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/doma.jpg', 2);

insert into articles (article_id, title, content, summary, date, image, author_id) values 
(11, 'Akaza', "<p>Akaza was a very muscular young man of average height with skin so fair it appeared bright green-tinged white, decorated by a pattern of thick blue lines, which resembled the criminal tattoos he had as a human. Akaza had short, bright pink hair that fluffed out around his head and inward-tilting yellow eyes with pink eyelashes and blue sclera that somewhat resembled cracked glass. The kanji for Upper Rank was etched into his right iris, and the daiji for Three was etched into his left.</p>

<p>Akaza was a headstrong, stubborn, and battle-crazed Social Darwinist who enjoyed fighting, especially against strong Demon Slayers. He purposefully drew out fights to savor every moment of it, always complimenting his opponents when they unleashed powerful techniques or landed blows on him, usually remarking that their techniques and swordsmanship were magnificent and intriguing. Akaza looked down on anybody he deemed weak, so much so that his skin would crawl at the sight of them. He genuinely respected those who were strong in his eyes, demanding to know their names, and would not stop until he found out; he remembered all the names of strong opponents of the past and committed them to memory as a tribute to their strength.</p>

<p>As the third highest-ranking member of the Twelve Kizuki, Akaza was an exceptionally powerful demon and the fourth strongest in existence after Doma, Kokushibo, and Muzan Kibutsuji. Even as a human child without martial arts training, Akaza could defeat and render grown men unconscious on his own. At the age of 18, after mastering the Soryu Style (素そ流りゅう式しき Soryū Shiki?) from Keizo, he singlehandedly annihilated 67 trained adult swordsmen with his bare fists, to the point where Muzan initially thought it was a demon who had killed all these men. Upon becoming a demon, his combat prowess only grew, eventually earning him the title of Upper Rank Three among the Twelve Kizuki, despite his growth rate being hindered by his refusal to eat women. Akaza was able to fight on par with the Flame Hashira Kyojuro Rengoku and kill him, and had also claimed the lives of numerous other Hashira and Demon Slayers in the past.</p>", "Akaza is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Three.", datetime(CURRENT_TIMESTAMP, 'LOCALTIME'), '/images/akaza.jpeg', 1);
